apiVersion: v1
appVersion: 1.0.758
description: A Helm chart for quarks-secret, a k8s operator to create secrets
home: https://github.com/cloudfoundry-incubator/quarks-secret
icon: https://cloudfoundry-incubator.github.io/quarks-helm/logo.png
keywords:
- quarks
- secret
- rotation
maintainers:
- email: project-quarks@googlegroups.com
  name: project-quarks
name: quarks-secret
sources:
- https://github.com/cloudfoundry-incubator/quarks-secret
version: 1.0.758
