{{- if .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quarks-job-persist-output
  {{- if .Values.global.operator.watchNamespace }}
  namespace: {{ .Values.global.operator.watchNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: quarks-job-persist-output
roleRef:
  kind: Role
  name: quarks-job-persist-output
  apiGroup: rbac.authorization.k8s.io
{{- end }}
