apiVersion: v1
appVersion: 1.0.218
description: A Helm chart for quarks-job, a k8s operator for quarks jobs
home: https://github.com/cloudfoundry-incubator/quarks-job
icon: https://cloudfoundry-incubator.github.io/quarks-helm/logo.png
keywords:
- quarks
- job
- output
maintainers:
- email: project-quarks@googlegroups.com
  name: project-quarks
name: quarks-job
sources:
- https://github.com/cloudfoundry-incubator/quarks-job
- https://github.com/cfcontainerizationbot/cf-operator-base
version: 1.0.218
